name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # Checks out the repository code so that the workflow can access it.

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3
      # Sets up Python version 3.12.3 to be used in the workflow.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install kybra
      # Upgrades pip to the latest version and installs the necessary dependencies:
      # pytest for running tests and kybra for the application.

    - name: Run tests
      run: python -m pytest tests
      # Runs the tests located in the 'tests' directory using pytest.

    - name: Build
      run: python src/main.py
      # Executes the main script located at 'src/main.py' to build the application.
